In [2]:
%load_ext autoreload
%autoreload 2

import numpy as np

SIZE = 4
def generate_data(length):
    label = np.random.randint(SIZE, size=length)
    data = []
    for i in label:
        zeros = np.zeros(SIZE)
        zeros[i] = 1
        data.append(zeros)
        
    data = np.array(data)
    return label, data

In [6]:
training_length = 10**4
validation_length = 10**3
training_label, training_data = generate_data(training_length)
validation_label, validation_data = generate_data(validation_length)

test_length = 10 ** 5
testing_label, testing_data = generate_data(test_length)

[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]
